### ISSUE TITLE
warning when "Load From URL"

### ISSUE THREAD

**Issue by ioggstream** [italia/api-oas-checker#109]
## Reproduce

0- Open Developer Tools
1- show the hamburger
2- click "From url"

## I expect

No warnings

## Instead

```
Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
    at input
    at div
    at InputContainer (https://deploy-preview-98--api-validator.netlify.app/994d85ad97c79ad11e0f.js:9845:17)
    at Input (https://deploy-preview-98--api-validator.netlify.app/994d85ad97c79ad11e0f.js:10005:35)
    at div
    at ModalBody (https://deploy-preview-98--api-validator.netlify.app/994d85ad97c79ad11e0f.js:198473:25)
    at div
    at div
    at div
    at Transition (https://deploy-preview-98--api-validator.netlify.app/994d85ad97c79ad11e0f.js:189407:30)
    at Fade (https://deploy-preview-98--api-validator.netlify.app/994d85ad97c79ad11e0f.js:196809:19)
    at div
    at Portal (https://deploy-preview-98--api-validator.netlify.app/994d85ad97c79ad11e0f.js:199669:29)
    at Modal (https://deploy-preview-98--api-validator.netlify.app/994d85ad97c79ad11e0f.js:198074:30)
    at Dialog (https://deploy-preview-98--api-validator.netlify.app/994d85ad97c79ad11e0f.js:2599:3)
    at LoadFromUrlButton (https://deploy-preview-98--api-validator.netlify.app/994d85ad97c79ad11e0f.js:3019:3)
    at Connect(LoadFromUrlButton) (https://deploy-preview-98--api-validator.netlify.app/994d85ad97c79ad11e0f.js:186283:68)
```

**Comment by ioggstream** [comment]
This was only related to the new-ui, so we can close.
